version: '3.7'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '1234:1234'
      - '1235:1235'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true